version: '3'
services:
  cat-schedule-detection:
    image: link_to_your_registry
    container_name: cat-schedule-detection
    restart: always
    ports:
      - "5000:5000"
    environment:
      TZ: Europe/Berlin
      RTSP_STREAM: "rtsp://WEBCAM_IP:554/stream2"
      MYSQL_DATABASE: cat
      MYSQL_PORT: 3306
      MYSQL_USER: cat
      MYSQL_PASSWORD: cat
      MYSQL_HOST: mariadb
    networks:
      - monitoring
    depends_on:
      - mariadb
    logging:
      driver: "json-file"
      options:
        max-size: "2m"

  mariadb:
    image: mariadb:latest
    container_name: cat-schedule-detection_db
    restart: always
    environment:
      TZ: Europe/Berlin
      MYSQL_DEFAULT_TIMEZONE: Europe/Berlin
      MYSQL_ROOT_PASSWORD: cat
      MYSQL_DATABASE: cat
      MYSQL_USER: cat
      MYSQL_PASSWORD: cat
      MYSQLD_INNODB_BUFFER_POOL_SIZE: "256M"
      MYSQLD_INNODB_LOG_FILE_SIZE: "64M"
      MYSQLD_INNODB_FLUSH_METHOD: "O_DIRECT"
      MYSQLD_INNODB_FLUSH_LOG_AT_TRX_COMMIT: "2"
      MYSQLD_INNODB_IO_CAPACITY: "2000"
      MYSQLD_INNODB_READ_IO_THREADS: "8"
      MYSQLD_INNODB_WRITE_IO_THREADS: "8"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - monitoring
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  mariadb-data:
    driver: local

networks:
  monitoring:
    driver: bridge